version: '3.9'

services:
  streamlit:
    context: ./web
    dockerfile: Dockerfile
    image: python:3.9
    command: sh -c "pip install streamlit && streamlit run chat.py"
    volumes:
      - ./web/chat.py:/app/chat.py
    ports:
      - "8501:8501"
    networks:
      - weaviate

  weaviate:
    image: semi-technologies/weaviate:latest
    context: ./db
    dockerfile: Dockerfile
    volumes:
      - ./db:/var/lib/weaviate
    ports:
      - "8080:8080"
    networks:
      - weaviate

networks:
  weaviate:
    driver: bridge

